from fpdf import FPDF
import uuid
import os

# =========================================
# PDF GENERATOR
# =========================================

def generate_pdf(prompt):

    os.makedirs(
        "generated_pdfs",
        exist_ok=True
    )

    # REMOVE COMMAND WORDS

    topic = (
        prompt
        .replace("create pdf about", "")
        .replace("make pdf about", "")
        .replace("generate pdf about", "")
        .strip()
    )

    # =====================================
    # CONTENT DATABASE
    # =====================================

    if "bhagat singh" in topic.lower():

        content = """
Bhagat Singh was one of India's greatest freedom fighters.

He was born on 28 September 1907 in Punjab.

Bhagat Singh fought bravely against British rule.

He became famous after the Lahore conspiracy case.

He sacrificed his life for India's freedom at the age of 23.

His slogan:
'Inquilab Zindabad'
became very popular.

Bhagat Singh remains a symbol of courage and patriotism.
"""

    else:

        content = f"""
This PDF contains information about:

{topic}

Generated by ULTRA JARVIS AI.
"""

    # =====================================
    # CREATE PDF
    # =====================================

    pdf = FPDF()

    pdf.add_page()

    pdf.set_font(
        "Arial",
        size=14
    )

    pdf.multi_cell(
        0,
        10,
        content
    )

    filename = (
        f"generated_pdfs/{uuid.uuid4()}.pdf"
    )

    pdf.output(filename)

    return filename